/* Designathon evidence: personas, flow rationale, degradation and disclosure. */
function caseStudyView(){
  const personas=[
    ['Dispatcher','Dinuka Fernando','Large planning screen · stable connection','Needs a feasible plan, live progress, and a defensible record of deferrals.','dispatch'],
    ['Loader','Kasun Silva','Shared warehouse tablet · busy loading dock','Needs the final stop sequence, reverse loading order, and a fast way to stop a short shipment.','loader'],
    ['Driver','Amal Perera','Personal phone · safely stopped · unreliable coverage','Needs one clear next action, offline capture, proof of delivery, and return-visit recovery.','delivery'],
    ['Store manager','Nimasha Perera','Outlet counter · desktop or phone','Needs order confirmation, expected arrival, deferral notice, receipt confirmation, and issue visibility.','store']
  ];
  const screens=[
    ['Order & track','Store manager','Shows stock health, suggested full-carton quantities, the 16:00 cutoff, and one shared status. It reduces phone calls and gives the outlet a reliable receipt trail.','store'],
    ['Plan & allocate','Dispatcher','Pairs the queue, stop sequence, vehicle, and operating checks on one large-screen workspace. Invalid assignments are blocked and deferrals require a reason.','dispatch'],
    ['Load in sequence','Loader','Turns the planned stop order into reverse loading order. Each shipment stays blocked until its carton count or issue is resolved.','loader'],
    ['Deliver & prove','Driver','Keeps the current stop, window, navigation, contact, exceptions, and proof of delivery within a phone-first flow designed for use while stopped.','delivery']
  ];
  return `${heading('Tech-Triathlon 2026 · Designathon','Relay connects every handoff.','A source-aligned case study for Waypoint Group’s shared delivery network.',`<button class="btn" data-action="reset-confirm">Reset demo</button><button class="btn primary" data-role="store">Start judge walkthrough ${icon('arrow')}</button>`)}
  <nav class="case-jump" aria-label="Case study sections"><a href="#case-problem">Problem</a><a href="#case-personas">Personas</a><a href="#case-flow">Screens</a><a href="#case-degradation">Degradation</a><a href="#case-decisions">Decisions</a><a href="#case-disclosure">Disclosure</a></nav>
  <section class="case-hero" id="case-problem"><div><span class="eyebrow">Problem framing</span><h2>One network. Three brands. Too many disconnected decisions.</h2><p>Waypoint Fresh, Style, and Tech share 60 vehicles, two depots, and limited daily capacity. Orders are re-entered into spreadsheets, plans depend on one dispatcher’s memory, loading lists become stale, and proof of delivery is fragmented across paper and calls.</p><p>Relay creates one explainable record from order confirmation through receipt. It prioritizes feasibility, role-to-role handoffs, and recovery when normal operations break down.</p></div><aside><b>High-fidelity scope</b><p>One complete Waypoint Fresh trip from Peliyagoda across all four roles, plus previews for Style and Tech. This slice makes the critical handoffs testable while the shared constraint model represents the wider network.</p><small>All records shown are synthetic. OUT001–OUT120 and VEH001–VEH060 follow the supplied dataset conventions.</small></aside></section>
  <section class="case-section" id="case-personas"><div class="case-heading"><span class="eyebrow">Four user personas</span><h2>Designed for where the work happens.</h2><p>Each persona is grounded in the role, device, connection, and information needs stated in the challenge booklet.</p></div><div class="persona-grid">${personas.map(([roleName,name,context,need,target])=>`<article class="persona-card"><span class="persona-avatar">${name.split(' ').map(part=>part[0]).join('')}</span><div><small>${roleName}</small><h3>${name}</h3></div><dl><dt>Working context</dt><dd>${context}</dd><dt>Primary need</dt><dd>${need}</dd></dl><button class="btn wide" data-role="${target}">Open ${roleName.toLowerCase()} view ${icon('arrow')}</button></article>`).join('')}</div></section>
  <section class="case-section" id="case-flow"><div class="case-heading"><span class="eyebrow">Connected screen flow & rationale</span><h2>Store → Plan → Load → Deliver → Confirm.</h2><p>A change made by one role becomes the next role’s trusted input. The prototype deliberately avoids separate, disconnected demos.</p></div><ol class="screen-flow">${screens.map(([title,roleName,rationale,target],index)=>`<li><span class="screen-number">${index+1}</span><div><small>${roleName}</small><h3>${title}</h3><p>${rationale}</p></div><button class="mini-btn" data-role="${target}">View screen ${icon('arrow')}</button></li>`).join('')}</ol></section>
  <section class="case-section degradation-case" id="case-degradation"><div class="case-heading"><span class="eyebrow">Named degradation scenario</span><h2>Connection lost in hill country.</h2></div><div class="degradation-layout"><div><h3>Why it matters</h3><p>Coverage can drop along the Kandy corridor and in rural districts. A driver or loader who loses signal must not lose a carton check, exception, arrival, or receipt—or accidentally make an unsafe routing change from stale data.</p><h3>Designed response</h3><p>Relay keeps safe field actions usable, timestamps them on the device, shows an explicit pending-update count, and reconciles the queue when coverage returns. Route changes remain protected while offline. Outstanding or deferred stops never appear complete.</p><button class="btn primary" data-action="show-degradation">Open the live failure state ${icon('arrow')}</button></div><div class="degradation-phone" aria-label="Offline state preview"><span>${icon('wifi')}</span><b>Connection lost</b><strong>3 updates waiting</strong><p>Loading and receipts stay available. Route changes require a connection.</p><small>Last synced 05:42</small></div></div></section>
  <section class="case-section" id="case-decisions"><div class="case-heading"><span class="eyebrow">Scope, domain rules & core tradeoff</span><h2>Explainability before invisible automation.</h2></div><div class="decision-grid"><article><h3>Core tradeoff</h3><p>Relay uses assisted planning with visible validation instead of a black-box auto-allocator. The dispatcher keeps control, but the system blocks infeasible weight, volume, refrigeration, access, depot, time, trip, and fuel choices.</p></article><article><h3>Prioritization</h3><p>Fresh windows, chilled capacity, van-only access, and repeat deferrals are made prominent because they create the highest service risk. Style mall windows and Tech fragile loads reuse the same planning model.</p></article><article><h3>Future capacity</h3><p>A 10-week depot × brand forecast view translates future volume into a staffing and fleet conversation, including explicit refrigerated-capacity needs ahead of festivals and paydays.</p></article><article><h3>Prototype boundary</h3><p>This is a high-fidelity front-end prototype. Allocation, forecasts, synchronization, contacts, navigation, and records are illustrative; no live backend or optimization engine is claimed.</p></article></div></section>
  <section class="case-section" id="case-style"><div class="case-heading"><span class="eyebrow">Style guide</span><h2>One operational language across four roles.</h2></div><div class="style-strip"><div><span class="swatch accent"></span><b>Deep green</b><small>Primary actions, feasible and complete</small></div><div><span class="swatch amber"></span><b>Amber</b><small>Attention, offline and timing risk</small></div><div><span class="swatch red"></span><b>Red</b><small>Blocked constraints and exceptions</small></div><div><span class="type-sample">Aa</span><b>Segoe UI / Arial</b><small>Self-contained system font stack</small></div></div><p class="case-note">Shared patterns include 44 px minimum controls, consistent status language, visible focus, semantic headings, reduced-motion support, and responsive layouts from 360–1440 px.</p></section>
  <section class="case-section" id="case-disclosure"><div class="case-heading"><span class="eyebrow">AI tool disclosure</span><h2>How AI assisted this submission.</h2></div><div class="disclosure-grid"><div><h3>AI-assisted</h3><p>Requirements extraction, gap analysis, source-alignment suggestions, front-end code revision, test expansion, copy refinement, and beginner documentation were assisted by OpenAI Codex during the final review.</p></div><div><h3>Human-led / existing work</h3><p>The original Relay concept, visual direction, interaction model, and submitted workspace were provided by the team. Final competition claims, design judgment, prototype demonstration, and submission decisions remain the team’s responsibility.</p></div><div><h3>Verification</h3><p>Official booklet requirements and supplied CSV schemas were checked directly. Automated browser tests exercise the connected workflow, exceptions, offline recovery, accessibility behaviors, and responsive layouts.</p></div></div></section>
  <footer class="case-footer"><div><b>Judge path</b><span>Start at Store, place the recommended order, continue through Dispatch, Warehouse, Delivery, then return to Store for the receipt.</span></div><button class="btn primary" data-role="store">Begin walkthrough ${icon('arrow')}</button></footer>`;
}

function showDegradation(){
  state=seed();caseStudyOpen=false;role='delivery';state.confirmed=true;state.ready=true;state.started=true;state.offline=true;state.pending=['Arrival saved','Exception saved','Receipt draft saved'];assigned().forEach(o=>{o.loaded=true;o.status='In transit';o.arrived=false;o.deferred=false;o.issue='';delete o.recipient;delete o.deliveredAt;});save();location.hash='delivery';render();toast('Failure scenario loaded: connection lost.');
}
