/* Designathon evidence: personas, flow rationale, degradation and disclosure. */
function caseStudyView(){
  const personas=[
    ['Dispatcher','Dinuka Fernando','Large planning screen · stable connection','Needs a feasible plan, live progress, and a defensible record of deferrals.','dispatch'],
    ['Loader','Kasun Silva','Shared warehouse tablet · busy loading dock','Needs the final stop sequence, reverse loading order, and a fast way to stop a short shipment.','loader'],
    ['Driver','Amal Perera','Personal phone · safely stopped · unreliable coverage','Needs one clear next action, offline capture, proof of delivery, and return-visit recovery.','delivery'],
    ['Store manager','Nimasha Perera','Outlet counter · desktop or phone','Needs order confirmation, expected arrival, deferral notice, receipt confirmation, and issue visibility.','store']
  ];
  const screens=[
    ['Order replenishment','Store manager','Stock health, full-carton suggestions and the 16:00 cutoff help a counter manager choose quantities quickly without a separate spreadsheet.','store'],
    ['Order tracking & ETA','Store manager','Order status, calculated arrival, delivery window and vehicle help the outlet prepare staff and space for the expected handoff.','store'],
    ['Receipt check','Store manager','Driver POD sits beside Confirm receipt and Report an issue, so the outlet can check cartons and record a discrepancy at the counter.','store'],
    ['Confirmed order queue','Dispatcher','Orders, windows and service risk appear together so a planner at a large screen can choose the next assignment.','dispatch'],
    ['Plan & validate','Dispatcher','Stop sequence, vehicle and seven checks expose an infeasible plan together on the dispatcher’s large screen before release.','dispatch'],
    ['Deferral decision','Dispatcher','A reason and impact note make a skipped outlet visible and defensible at the planning desk when this run cannot serve it.','dispatch'],
    ['Delivery & receipt follow-up','Dispatcher','The dispatch overview keeps delivered stops complete while identifying the order, outlet and receipt discrepancy for reconciliation.','dispatch'],
    ['Loading manifest','Loader','Reverse stop order and carton counts guide fast loading on a shared warehouse tablet without burying the next shipment.','loader'],
    ['Loading exception','Loader','A blocked shipment and resolution note let dock staff stop a short or damaged load before it leaves the bay.','loader'],
    ['Next stop','Driver','The current stop, window, contact and next action stay prominent on a phone used only while safely stopped.','delivery'],
    ['Delivery exception','Driver','A reason, details and return-visit path keep an undelivered stop visible when access or goods prevent handoff.','delivery'],
    ['Proof of delivery','Driver','Carton verification, recipient and time create a clear delivery record on the phone for Store and Dispatch to inspect.','delivery']
  ];
  return `${heading('Tech-Triathlon 2026 · Designathon','Relay connects every handoff.','A source-aligned case study for Waypoint Group’s shared delivery network.',`<button class="btn" data-action="reset-confirm">Reset demo</button><button class="btn primary" data-role="store">Start judge walkthrough ${icon('arrow')}</button>`)}
  <nav class="case-jump" aria-label="Case study sections"><a href="#case-problem">Problem</a><a href="#case-personas">Personas</a><a href="#case-flow">Screens</a><a href="#case-degradation">Degradation</a><a href="#case-decisions">Decisions</a><a href="#case-disclosure">Disclosure</a></nav>
  <section class="case-hero" id="case-problem"><div><span class="eyebrow">Problem framing</span><h2>One network. Three brands. Too many disconnected decisions.</h2><p>Waypoint Fresh, Style, and Tech share 60 vehicles, two depots, and limited daily capacity. Orders are re-entered into spreadsheets, plans depend on one dispatcher’s memory, loading lists become stale, and proof of delivery is fragmented across paper and calls.</p><p>Relay creates one explainable record from order confirmation through receipt. It prioritizes feasibility, role-to-role handoffs, and recovery when normal operations break down.</p></div><aside><b>High-fidelity scope</b><p>One complete Waypoint Fresh trip from Peliyagoda across all four roles, plus previews for Style and Tech. This slice makes the critical handoffs testable while the shared constraint model represents the wider network.</p><small>All records shown are synthetic. OUT001–OUT120 and VEH001–VEH060 follow the supplied dataset conventions.</small></aside></section>
  <section class="case-section" id="case-personas"><div class="case-heading"><span class="eyebrow">Four user personas</span><h2>Designed for where the work happens.</h2><p>One Relay application serves four distinct people. Each account has a fixed role and opens only its relevant workspace; shared delivery state connects their work. Waypoint assigns roles: public signup and role self-selection are intentionally absent. Switch demo account is a judge convenience, not employee navigation.</p></div><div class="persona-grid">${personas.map(([roleName,name,context,need,target])=>`<article class="persona-card"><span class="persona-avatar">${name.split(' ').map(part=>part[0]).join('')}</span><div><small>${roleName}</small><h3>${name}</h3></div><dl><dt>Working context</dt><dd>${context}</dd><dt>Primary need</dt><dd>${need}</dd></dl><button class="btn wide" data-role="${target}">Open ${roleName.toLowerCase()} view ${icon('arrow')}</button></article>`).join('')}</div></section>
  <section class="case-section" id="case-flow"><div class="case-heading"><span class="eyebrow">Connected screen flow & rationale</span><h2>Store → Plan → Load → Deliver → Confirm.</h2><p>A change made by one role becomes the next role’s trusted input. The prototype deliberately avoids separate, disconnected demos.</p></div><ol class="screen-flow">${screens.map(([title,roleName,rationale,target],index)=>`<li><span class="screen-number">${index+1}</span><div><small>${roleName}</small><h3>${title}</h3><p>${rationale}</p></div><button class="mini-btn" data-role="${target}">View screen ${icon('arrow')}</button></li>`).join('')}</ol></section>
  <section class="case-section degradation-case" id="case-degradation"><div class="case-heading"><span class="eyebrow">Named degradation scenario</span><h2>Connection lost during delivery.</h2></div><div class="degradation-layout"><div><h3>Why it matters</h3><p>The live example uses the Colombo route. Coverage loss is especially relevant in hill country, along the Kandy corridor and in rural districts; field staff still need reliable carton checks, exceptions, arrivals and receipts.</p><h3>Offline state</h3><p>On a driver’s phone or loader’s tablet, safe actions remain usable and a pending-update count shows what awaits synchronization. Route changes stay protected, and outstanding stops remain visible.</p><h3>Reconnected state</h3><p>When coverage returns, the queued updates reconcile and the count clears, giving field staff a clear sign that their saved work is current.</p><button class="btn primary" data-action="show-degradation">Load failure demo as Driver ${icon('arrow')}</button></div><div class="degradation-phone" aria-label="Offline state preview"><span>${icon('wifi')}</span><b>Connection lost</b><strong>3 updates waiting</strong><p>Loading and receipts stay available. Route changes require a connection.</p><small>Last synced 05:42</small></div></div></section>
  <section class="case-section" id="case-decisions"><div class="case-heading"><span class="eyebrow">Scope, domain rules & core tradeoff</span><h2>Explainability before invisible automation.</h2></div><div class="decision-grid"><article><h3>Core tradeoff</h3><p>Relay uses assisted planning with visible validation instead of a black-box auto-allocator. The dispatcher keeps control, but the system blocks infeasible weight, volume, refrigeration, access, depot, time, trip, and fuel choices.</p></article><article><h3>Prioritization</h3><p>Fresh windows, chilled capacity, van-only access, and repeat deferrals are made prominent because they create the highest service risk. Style mall windows and Tech fragile loads reuse the same planning model.</p></article><article><h3>Future capacity</h3><p>A 10-week depot × brand forecast view translates future volume into a staffing and fleet conversation, including explicit refrigerated-capacity needs ahead of festivals and paydays.</p></article><article><h3>Prototype boundary</h3><p>This is a high-fidelity front-end prototype. Allocation, forecasts, synchronization, contacts, navigation, and records are illustrative; no live backend or optimization engine is claimed.</p></article></div></section>
  <section class="case-section" id="case-style"><div class="case-heading"><span class="eyebrow">Style guide</span><h2>One operational language across four roles.</h2></div><div class="style-strip"><div><span class="swatch accent"></span><b>Deep green</b><small>Primary actions, feasible and complete</small></div><div><span class="swatch amber"></span><b>Amber</b><small>Attention, offline and timing risk</small></div><div><span class="swatch red"></span><b>Red</b><small>Blocked constraints and exceptions</small></div><div><span class="type-sample">Aa</span><b>Segoe UI / Arial</b><small>Self-contained system font stack</small></div></div><p class="case-note">Shared patterns include 44 px minimum controls, consistent status language, visible focus, semantic headings, reduced-motion support, and responsive layouts from 360–1440 px.</p></section>
  <section class="case-section" id="case-disclosure"><div class="case-heading"><span class="eyebrow">AI tool disclosure</span><h2>How AI assisted this submission.</h2></div><div class="disclosure-grid"><div><h3>AI-assisted</h3><p>Requirements extraction, gap analysis, source-alignment suggestions, front-end code revision, test expansion, copy refinement, and beginner documentation were assisted by OpenAI Codex during the final review.</p></div><div><h3>Human-led / existing work</h3><p>The original Relay concept, visual direction, interaction model, and submitted workspace were provided by the team. Final competition claims, design judgment, prototype demonstration, and submission decisions remain the team’s responsibility.</p></div><div><h3>Verification</h3><p>Official booklet requirements and supplied CSV schemas were checked directly. Automated browser tests exercise the connected workflow, exceptions, offline recovery, accessibility behaviors, and responsive layouts.</p></div></div></section>
  <footer class="case-footer"><div><b>Judge path</b><span>Start at Store, place the recommended order, continue through Dispatch, Warehouse, Delivery, then return to Store for the receipt.</span></div><button class="btn primary" data-role="store">Begin walkthrough ${icon('arrow')}</button></footer>`;
}

function showDegradation(){
  enterAccount('driver');state=seed();caseStudyOpen=false;role='delivery';state.confirmed=true;state.ready=true;state.started=true;state.offline=true;state.pending=['Arrival saved','Exception saved','Receipt draft saved'];assigned().forEach(o=>{o.loaded=true;o.status='In transit';o.arrived=false;o.deferred=false;o.issue='';delete o.recipient;delete o.deliveredAt;});save();location.hash='delivery';render();toast('Failure scenario loaded: connection lost.');
}
