import { roles, workflow, faqs } from './data.js';
import { brand, dispatchPreview, planningPreview, phonePreview } from './previews.js';

const arrow = '<span aria-hidden="true">↗</span>';
const sectionHead = (eyebrow, title, copy = '') => `<div class="section-heading"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2>${copy ? `<p class="section-copy">${copy}</p>` : ''}</div>`;
const nav = () => `<header class="site-header"><nav class="container nav" aria-label="Main navigation"><a class="brand" href="#" aria-label="Relay home">${brand()}</a><button class="menu-toggle" aria-expanded="false" aria-controls="nav-links">Menu <span aria-hidden="true">☰</span></button><div id="nav-links" class="nav-links"><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#teams">For your team</a><a href="#faq">FAQ</a></div><a class="button small" href="#platform">Explore Relay ${arrow}</a></nav></header>`;
const hero = () => `<section class="hero container"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> DELIVERY OPERATIONS, ORCHESTRATED</p><h1>Every delivery.<br>One coordinated <em>operation.</em></h1><p class="hero-description">From the first order to the final receipt. Relay brings planning, loading, drivers and receiving teams into one clear workflow.</p><div class="actions"><a class="button" href="#platform">Explore the platform ${arrow}</a><a class="text-link" href="#workflow">See how it works <span aria-hidden="true">→</span></a></div><p class="hero-note">Built around the people who keep deliveries moving.</p></div><figure class="hero-product">${dispatchPreview()}<figcaption><span><span class="dot"></span> ONE WORKFLOW. EVERY HANDOFF.</span><span>Product interface overview · Illustrative records</span></figcaption></figure></section>`;
const values = () => `<div class="value-strip container">${['Constraint-aware planning', 'Connected operational handoffs', 'Delivery & receipt visibility', 'Four focused workspaces'].map((x,i)=>`<div><span aria-hidden="true">${['⊞','⇄','◎','▦'][i]}</span>${x}</div>`).join('')}</div>`;
const problem = () => `<section class="container section problem">${sectionHead('LESS CHASING. MORE CLARITY.', 'The work is connected.<br>Your tools should be, too.', 'A spreadsheet for the plan. A call to the warehouse. A message about a missed stop. Every disconnected handoff makes the whole operation harder to see.')}<div class="comparison"><div><small>SCATTERED OPERATIONS</small><p>Separate plans. Missing context.</p><ul><li>Updates spread across calls and sheets</li><li>Exceptions without a clear next action</li><li>Decisions that stay with one person</li></ul></div><div class="with-relay"><small>WITH RELAY</small><p>One workflow. Shared context.</p><ul><li>A connected order-to-receipt journey</li><li>Outstanding work kept in view</li><li>Recorded reasons behind deferrals</li></ul></div></div></section>`;
const workflowSection = () => `<section id="workflow" class="workflow-section section"><div class="container">${sectionHead('FROM DEMAND TO DONE', 'A handoff, not a handbrake.', 'Give every team the context to take the next step.')}<ol class="workflow">${workflow.map(([title,copy,num])=>`<li><span class="step-num">${num}</span><h3>${title}</h3><p>${copy}</p></li>`).join('')}</ol><div class="workflow-foot"><span>ORDER INTAKE</span><div></div><b>One connected delivery cycle</b><div></div><span>FINAL RECEIPT</span></div></div></section>`;
const planning = () => `<section id="platform" class="container section split planning"><div>${sectionHead('01 / PLAN WITH CONTEXT', 'Complex constraints.<br>One clear plan.', 'A delivery plan has to work outside the spreadsheet. Bring vehicle capacity, temperature, access and timing into the same decision.')}<ul class="feature-list"><li><b>Know what fits.</b><span>Check weight, volume and vehicle compatibility before release.</span></li><li><b>Make the tradeoffs visible.</b><span>See why an assignment is blocked. Record why an order is deferred.</span></li><li><b>Give the warehouse a clear handoff.</b><span>Turn the confirmed plan into a sequenced loading manifest.</span></li></ul><a class="text-link" href="#teams">Meet the dispatcher workspace →</a></div><figure class="planning-figure">${planningPreview()}<figcaption>Assignment and deferral UI representation · Illustrative records</figcaption><div class="figure-caption"><span>↳</span> A reason behind the decision.<br>A next step for the team.</div></figure></section>`;
const execution = () => `<section id="teams" class="teams-section section"><div class="container">${sectionHead('02 / PUT THE PLAN TO WORK', 'One operation.<br>The right view for every team.', 'Focused workspaces. Clear next actions. The same delivery journey.')}<div class="role-tabs" role="tablist" aria-label="Explore team workspaces">${roles.map((r,i)=>`<button role="tab" id="tab-${r.screen}" aria-selected="${i===0}" aria-controls="role-panel" tabindex="${i===0?0:-1}" data-role="${i}"><span>0${i+1}</span>${r.name}</button>`).join('')}</div><div id="role-panel" class="role-panel" role="tabpanel" aria-labelledby="tab-dispatch" tabindex="0"></div></div></section>`;
const visibility = () => `<section class="container section split visibility"><div class="activity-preview"><div class="panel-title">R-07 / Delivery progress <span class="badge">In progress</span></div><div class="activity-stat"><strong>02<span>/04</span></strong><div>stops delivered<small>Outstanding work stays visible.</small></div></div><ol class="activity-list"><li><span class="activity-dot"></span><div><b>Delivery recorded</b><p>Riverside Market · 48 cartons · Recipient captured</p></div><small>05:18</small></li><li><span class="activity-dot"></span><div><b>Receipt confirmed</b><p>Riverside Market · Receiving team</p></div><small>05:24</small></li><li class="attention"><span class="activity-dot"></span><div><b>Access delayed</b><p>Parkside Store · Return visit required</p></div><span class="badge amber">Open</span></li></ol><p class="preview-caption">Delivery and receipt states · Illustrative records</p></div><div>${sectionHead('03 / KEEP THE EXCEPTIONS IN VIEW', 'A delivery isn’t done<br>until the loop is closed.', 'Keep delivery outcomes, receiving confirmations and unresolved issues distinct. Give the team a clear view of what still needs attention.')}<div class="editorial-points"><p><b>Delivered is a milestone.</b><br>Review the recipient, carton count and delivery time.</p><p><b>Received closes the loop.</b><br>Stores confirm what arrived or raise a discrepancy.</p><p><b>Unresolved means visible.</b><br>Deferred stops stay outstanding for a return visit.</p></div></div></section>`;
const benefits = () => `<section class="benefits section"><div class="container">${sectionHead('BUILT AROUND THE OPERATING DAY', 'More control at every handoff.')}<div class="three-col">${[['01','Coordinate with context','Keep planning decisions and delivery outcomes connected to the order they belong to.'],['02','Prepare with confidence','Review practical constraints before releasing work to the warehouse and the road.'],['03','Follow through on exceptions','Capture issues, record resolutions and keep unfinished deliveries in the workflow.']].map(([n,t,p])=>`<article><span class="index">${n}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></div></section>`;
const implementation = () => `<section class="container section adoption">${sectionHead('BRING RELAY INTO YOUR OPERATION', 'Start with your workflow.')}<div class="three-col">${[['Map the operating day','Identify your locations, fleet requirements and delivery constraints.'],['Align the handoffs','Bring dispatchers, loaders, drivers and receiving teams into a shared process.'],['Run and review','Plan the work, capture delivery outcomes and review outstanding exceptions.']].map(([t,p],i)=>`<article><span class="step-num">0${i+1}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></section>`;
const trust = () => `<section id="trust" class="container trust"><div><p class="eyebrow">ACCESS WITH PURPOSE</p><h2>The right workspace.<br>The right responsibilities.</h2></div><div><p>Authenticated accounts connect people to their assigned role. Server-side permission checks protect access to backend routes.</p><div class="trust-tags"><span>Role-specific workspaces</span><span>Authenticated sessions</span><span>Server-side access checks</span></div></div></section>`;
const faq = () => `<section id="faq" class="container section faq">${sectionHead('A FEW MORE DETAILS', 'Good questions.<br>Clear answers.')}<div>${faqs.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
const finalCTA = () => `<section class="container final-cta"><p class="eyebrow">FROM FIRST ORDER TO FINAL RECEIPT</p><h2>Bring your delivery operation<br>onto the same page.</h2><p>See how planning, execution and receiving fit together in Relay.</p><a class="button light" href="#platform">Explore Relay ${arrow}</a><a class="cta-secondary" href="#teams">Find your team’s workspace →</a></section>`;
const footer = () => `<footer class="container footer"><div><a class="brand" href="#" aria-label="Relay home">${brand()}</a><p>Delivery operations, orchestrated.</p></div><nav aria-label="Footer navigation"><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#teams">Teams</a><a href="#trust">Access & security</a><a href="#faq">FAQ</a></nav><div class="footer-bottom"><span>© ${new Date().getFullYear()} Zephyrus Relay</span><span>From the first order to the final receipt.</span></div></footer>`;

document.querySelector('#app').innerHTML = `${nav()}<main id="main" tabindex="-1">${hero()}${values()}${problem()}${workflowSection()}${planning()}${execution()}${visibility()}${benefits()}${implementation()}${trust()}${faq()}${finalCTA()}</main>${footer()}`;

function setRole(index, focus = false) {
  const role = roles[index];
  document.querySelectorAll('[data-role]').forEach((tab, i) => {
    tab.setAttribute('aria-selected', String(i === index));
    tab.tabIndex = i === index ? 0 : -1;
    if (focus && i === index) tab.focus();
  });
  const panel = document.querySelector('#role-panel');
  panel.setAttribute('aria-labelledby', `tab-${role.screen}`);
  panel.innerHTML = `<div class="role-copy"><p class="eyebrow">THE ${role.name.toUpperCase()} WORKSPACE</p><h3>${role.label}</h3><p>${role.copy}</p><ul>${role.items.map(x=>`<li><span aria-hidden="true">✓</span>${x}</li>`).join('')}</ul><span class="role-foot">One delivery cycle. A focused workspace for your part.</span></div><figure class="phone-stage">${phonePreview(role.screen)}<figcaption>Workspace representation<br>Illustrative records</figcaption></figure>`;
}
setRole(0);
document.querySelector('.role-tabs').addEventListener('click', e => {
  const tab = e.target.closest('[data-role]');
  if (tab) setRole(Number(tab.dataset.role));
});
document.querySelector('.role-tabs').addEventListener('keydown', e => {
  const current = Number(e.target.closest('[data-role]')?.dataset.role);
  if (!Number.isInteger(current)) return;
  const next = { ArrowRight: (current + 1) % roles.length, ArrowLeft: (current + roles.length - 1) % roles.length, Home: 0, End: roles.length - 1 }[e.key];
  if (next !== undefined) { e.preventDefault(); setRole(next, true); }
});
const menu = document.querySelector('.menu-toggle');
const closeMenu = () => { menu.setAttribute('aria-expanded', 'false'); document.querySelector('.nav-links').classList.remove('open'); };
menu.addEventListener('click', () => { const open = menu.getAttribute('aria-expanded') !== 'true'; menu.setAttribute('aria-expanded', String(open)); document.querySelector('.nav-links').classList.toggle('open', open); });
document.querySelectorAll('.nav-links a').forEach(link => link.addEventListener('click', closeMenu));
document.addEventListener('keydown', e => { if (e.key === 'Escape' && menu.getAttribute('aria-expanded') === 'true') { closeMenu(); menu.focus(); } });
const header = document.querySelector('.site-header');
window.addEventListener('scroll', () => header.classList.toggle('scrolled', scrollY > 12), { passive: true });
