export const brand = () => '<span class="brand-mark" aria-hidden="true">⇄</span><span>relay<span class="brand-dot">.</span></span>';
const badge = (text, amber = false) => `<span class="badge ${amber ? 'amber' : ''}">${text}</span>`;
const check = text => `<div class="check-row"><span aria-hidden="true">✓</span>${text}</div>`;

// Presentation-only compositions of the current operational UI. No application state or customer records.
export function dispatchPreview() {
  return `<div class="browser-frame"><div class="browser-top"><span class="window-dots" aria-hidden="true">● ● ●</span><span>Relay / Dispatcher workspace</span><span class="secure-label">Delivery operations</span></div>
    <div class="app-preview"><aside class="preview-sidebar"><div class="brand">${brand()}</div><small>WORKSPACE</small><div class="side-active">▦ &nbsp; Dispatch</div><div>▤ &nbsp; Manifest</div><div>◷ &nbsp; Activity</div><div class="sidebar-foot"><span class="avatar">DP</span> Dispatcher</div></aside>
    <div class="preview-main"><div class="preview-heading"><div><small>OPERATING DAY · CENTRAL DEPOT</small><h3>Next-day dispatch</h3><p>Allocate the confirmed queue and explain every deferral.</p></div><span class="app-button">✓ &nbsp; Confirm plan</span></div>
    <div class="pulse"><div><span>Awaiting decision</span><strong>03 <small>orders</small></strong></div><div><span>Planned on R-07</span><strong>04 <small>stops</small></strong></div><div><span>Weight / volume</span><strong>68<small>% · 17.9 / 26.4 m³</small></strong></div><div><span>Needs attention</span><strong class="amber-text">01 <small>access restriction</small></strong></div></div>
    <div class="runbar"><b><span class="dot"></span> R-07 · Fresh · Central</b><span>04:45 departure</span>${badge('Planning')}</div>
    <div class="dispatch-grid"><section class="queue"><div class="panel-title">Order queue <span>03</span></div><div class="order selected"><div><b>ORD-2847</b>${badge('Chilled')}</div><strong>Riverside Market</strong><p>48 cartons · 620 kg</p><small>05:00–08:00 · Rear dock</small></div><div class="order"><div><b>ORD-2848</b>${badge('Ambient')}</div><strong>Parkside Store</strong><p>32 cartons · 410 kg</p><small>06:00–09:00 · Street access</small></div><div class="order"><div><b>ORD-2849</b>${badge('Van only', true)}</div><strong>Garden Express</strong><p>18 cartons · 230 kg</p><small>Vehicle access review needed</small></div></section>
    <section class="route-panel"><div class="panel-title">Route & stops <span>R-07</span></div><div class="route-diagram" aria-label="Schematic route connecting the depot and four stops"><svg viewBox="0 0 420 195" role="img" aria-label="Four sequenced delivery stops from the depot"><path class="map-road" d="M0 40L420 140M40 0L240 195M280 0L160 195M0 160L420 50M370 0L320 195M0 100H420"/><path class="map-route" d="M55 140L130 75L220 110L295 52L360 104"/><g class="map-nodes"><circle cx="55" cy="140" r="13"/><circle cx="130" cy="75" r="13"/><circle cx="220" cy="110" r="13"/><circle cx="295" cy="52" r="13"/><circle cx="360" cy="104" r="13"/></g><g class="map-labels"><text x="55" y="144">D</text><text x="130" y="79">1</text><text x="220" y="114">2</text><text x="295" y="56">3</text><text x="360" y="108">4</text></g></svg><small>Schematic route · not to scale</small></div><div class="stop-row"><span class="stop-number">1</span><div><b>Riverside Market</b><small>48 cartons · Rear dock</small></div><b>05:09</b></div><div class="stop-row"><span class="stop-number">2</span><div><b>Harbour Fresh</b><small>36 cartons · Rear dock</small></div><b>05:32</b></div><div class="route-note">✓ &nbsp; Review the plan, then release to the warehouse.</div></section>
    <section class="vehicle-panel"><div class="panel-title">Vehicle & feasibility</div><div class="vehicle-name">▱ &nbsp; VEH003</div><p>Reefer truck · Bay 03</p><div class="capacity-label"><span>Weight capacity</span><b>68%</b></div><div class="meter"><i></i></div>${['Weight & volume', 'Temperature', 'Outlet access', 'Fuel allowance', 'Trips & time', 'Delivery windows'].map(check).join('')}<div class="feasible">✓ &nbsp; Assigned stops fit</div></section></div></div></div></div>`;
}

export function planningPreview() {
  return `<div class="planning-preview"><div class="panel-title">Assignment review ${badge('Needs review', true)}</div><div class="assignment"><span class="avatar">03</span><div><h3>VEH003 · Reefer truck</h3><p>R-07 / Fresh delivery run</p></div></div><div class="constraint-grid">${['Weight capacity', 'Volume capacity', 'Temperature', 'Delivery window'].map(check).join('')}</div><div class="blocker"><b>! &nbsp; Outlet requires a van</b><p>Garden Express cannot be assigned to this truck. Select a compatible vehicle or record a deferral.</p></div><div class="decision"><small>DEFERRAL REASON</small><p>Van-only access. Hold for a compatible vehicle.</p><span>Decision stays with the order ↗</span></div></div>`;
}

export function phonePreview(role = 'driver') {
  const content = {
    driver: `<small>DELIVERY / R-07</small><h3>Your next stop.</h3>${badge('In transit')}<div class="phone-route"><span>1</span><i></i><span>2</span><i></i><span>3</span></div><div class="phone-card"><small>STOP 1 OF 4</small><h4>Riverside Market</h4><p>Rear dock · Receiving team</p><hr><div class="phone-stat"><b>48 <small>cartons</small></b><b>05:09 <small>planned arrival</small></b></div></div><div class="phone-hint">Count the cartons with the recipient, then record the delivery receipt.</div><div class="app-button">Record arrival &nbsp; →</div><p class="phone-link">Report a delivery issue</p>`,
    loader: `<small>WAREHOUSE / BAY 03</small><h3>Ready for the road.</h3>${badge('Loading in progress')}<div class="phone-card"><small>LOAD LAST STOP FIRST</small><h4>Shipment 3 of 4</h4><p>Harbour Fresh · 36 cartons</p><hr>${check('Produce · 24 cartons')}${check('Dairy · 12 cartons')}</div><div class="phone-hint">Check each shipment before confirming the vehicle is loaded.</div><div class="app-button">Confirm loaded &nbsp; ✓</div><p class="phone-link">Missing / issue</p>`,
    store: `<small>STORE / ORDER TRACKING</small><h3>Delivery received.</h3>${badge('Delivered')}<div class="phone-card"><small>ORD-2847 / DELIVERY RECEIPT</small><h4>Riverside Market</h4><p>R-07 · VEH003</p><hr>${check('48 cartons delivered')}${check('Recipient recorded')}${check('Delivery time captured')}</div><div class="phone-hint">Check the cartons against the receipt to complete the handoff.</div><div class="app-button">Confirm receipt &nbsp; ✓</div><p class="phone-link">Report an issue</p>`,
    dispatch: `<small>DISPATCH / R-07</small><h3>The day, in view.</h3>${badge('Delivery in progress')}<div class="phone-card"><small>ROUTE PROGRESS</small><h4>2 of 4 delivered</h4><p>2 stops remaining</p><hr>${check('Riverside · Delivered')}${check('Harbour · Delivered')}<div class="check-row amber-text">! &nbsp; Parkside · Access delayed</div></div><div class="phone-hint">Outstanding stops stay visible until their delivery is resolved.</div><div class="app-button">Review route &nbsp; →</div><p class="phone-link">View delivery receipts</p>`,
  };
  return `<div class="phone"><div class="phone-top"><b>9:41</b><span aria-hidden="true">● ▰</span></div><div class="phone-brand">${brand()}<span>☰</span></div><div class="phone-body">${content[role]}</div><div class="phone-bottom" aria-hidden="true"></div></div>`;
}
